@startuml

!include ./style.puml

start

title Adding a Lesson to an existing Group

:Enter ""addlsn"" command;

if () then ([valid command])

            :Parse the ""addlsn"" command
            to get group and lesson number;

    if () then ([tutorial group exists])

	    if () then ([lesson number does not exist])
            :Create a new set of Attendance
            and Participation records;

            :Create the new Lesson with the new records;

	    :Add the new Lesson to the Group;

            :Show a success message;
	    else
	     :Show duplicate lesson error message;
	    endif



    else ([else])
            :Show invalid group error message;
    endif

else ([else])

    :Show an
    invalid command
    error message;
endif

stop

@enduml
