@startuml
!include style.puml
skinparam ActorFontColor black


Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR_T1
Participant ":Logic" as logic LOGIC_COLOR_T1
Participant ":Model" as model MODEL_COLOR_T1
Participant ":Storage" as storage STORAGE_COLOR_T1

user -[USER_COLOR]> ui : "delgrp grp/G04"
activate ui UI_COLOR_T1

ui -[UI_COLOR_T1]> logic : execute("delgrp grp/G04")
activate logic LOGIC_COLOR_T1

logic -[LOGIC_COLOR_T1]> model : deleteGroup(target)
activate model MODEL_COLOR_T1

model -[MODEL_COLOR_T1]-> logic
deactivate model

logic -[LOGIC_COLOR_T1]> storage : saveSerenity(serenity)
activate storage STORAGE_COLOR_T1

storage -[STORAGE_COLOR_T1]> storage : Save to file
activate storage STORAGE_COLOR
storage --[STORAGE_COLOR_T1]> storage
deactivate storage

storage --[STORAGE_COLOR_T1]> logic
deactivate storage

logic --[LOGIC_COLOR_T1]> ui
deactivate logic

ui--[UI_COLOR_T1]> user
deactivate ui
@enduml
