@startuml
!include style.puml
skinparam ActorFontColor black


Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR_T1
Participant ":Logic" as logic LOGIC_COLOR_T1
Participant ":Model" as model MODEL_COLOR_T1
Participant ":Storage" as storage STORAGE_COLOR_T1

user -[#black]> ui : "delgrp grp/G04"
activate ui UI_COLOR_T1

ui -[#black]> logic : execute("delgrp grp/G04")
activate logic LOGIC_COLOR_T1

logic -[#black]> model : deleteGroup(target)
activate model MODEL_COLOR_T1

model --[#black]> logic
deactivate model

logic -[#black]> storage : saveSerenity(serenity)
activate storage STORAGE_COLOR_T1

storage -[#black]> storage : Save to file
activate storage STORAGE_COLOR
storage --[#black]> storage
deactivate storage

storage --[#black]> logic
deactivate storage

logic --[#black]> ui
deactivate logic

ui--[#black]> user
deactivate ui
@enduml
