@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR_T1
    Class Logic LOGIC_COLOR_T1
    Class Storage STORAGE_COLOR_T1
    Class Model MODEL_COLOR_T1
    Class Main MAIN_COLOR
    Class Commons COMMONS_COLOR
}

Class "<$user>" as User ORANGE_COLOR
Class "<$documents>" as File ORANGE_COLOR


UI -[UI_COLOR_T1]> Logic
UI -right[UI_COLOR_T1]-> Model
Logic -[LOGIC_COLOR_T1]-> Storage
Logic -down[LOGIC_COLOR_T1]-> Model
Main -[MAIN_COLOR]-> UI
Main -[MAIN_COLOR]-> Logic
Main -[MAIN_COLOR]-> Storage
Main -up[MAIN_COLOR]-> Model

Storage .right[STORAGE_COLOR_T1].>File
User .[ORANGE_COLOR].> UI
@enduml
