@startuml
!include style.puml
skinparam {
arrowThickness 1.1
arrowColor MODEL_COLOR_T1
classBackgroundColor MODEL_COLOR_T1
classBackgroundColor<<HiddenOutside>> #FFFFFF
classBorderColor<<HiddenOutside>> #FFFFFF
classFontColor<<HiddenOutside>> #FFFFFF
classStereotypeFontColor<<HiddenOutside>> #FFFFFF
}

Class hideOutside <<HiddenOutside>>

Package Model <<Rectangle>>{
Interface ObservableList <<Interface>>
Interface Model <<Interface>>
Class ReadOnlyUserPrefs <<Interface>>
Interface UniqueList <<Interface>>
Class ModelManager
Class UserPrefs
Class UniqueXYZList
Class XYZManager
}

Model .left.> ObservableList : \t
hideOutside ..> Model :\t
ModelManager o-down-> XYZManager : \t
ModelManager o-right-> UserPrefs : \t
XYZManager o-left->"0..*"UniqueXYZList :\t
UniqueXYZList .up.|> UniqueList : \t
ModelManager .up.|> Model : \t
UserPrefs .up.|> ReadOnlyUserPrefs :\t

note right of XYZManager
XYZManager = GroupManager,
StudentManager, etc

UniqueXYZList = UniqueGroupList,
UniqueStudentList, etc
end note

@enduml
