@startuml
skinparam linetype ortho
!include style.puml

hide member

skinparam {
arrowThickness 1.1
arrowColor STORAGE_COLOR_T1
classBackgroundColor STORAGE_COLOR_T1
classBackgroundColor<<HiddenOutside>> #FFFFFF
classBorderColor<<HiddenOutside>> #FFFFFF
classFontColor<<HiddenOutside>> #FFFFFF
classStereotypeFontColor<<HiddenOutside>> #FFFFFF
}

Class hideOutside <<HiddenOutside>>

Package "Storage\t\t\t" <<Rectangle>>  {
Class StorageManager
Interface Storage <<Interface>>
Interface SerenityStorage <<Interface>>
Interface UserPrefStorage <<Interface>>
Interface QuestionStorage <<Interface>>
Class JsonUserPrefsStorage
Class JsonSerenityStorage
Class JsonQuestionStorage
}

hideOutside  ..> Storage
StorageManager .u.|> Storage
StorageManager o-r-> SerenityStorage
StorageManager o-l-> UserPrefStorage
StorageManager o-d-> QuestionStorage
JsonUserPrefsStorage .u.|> UserPrefStorage
JsonSerenityStorage .u.|> SerenityStorage
JsonQuestionStorage .u.|> QuestionStorage
@enduml
