@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Package "Storage\t\t\t" <<Rectangle>>  {
Class StorageManager
Interface Storage <<Interface>>
Interface SerenityStorage <<Interface>>
Interface UserPrefStorage <<Interface>>
Interface QuestionStorage <<Interface>>
Class JsonUserPrefsStorage
Class JsonSerenityStorage
Class JsonQuestionStorage
}


class "  " #FFFFFF
"  " ..> Storage
StorageManager .u.|> Storage
StorageManager o-r-> SerenityStorage
StorageManager o-l-> UserPrefStorage
StorageManager o-d-> QuestionStorage
JsonUserPrefsStorage .u.|> UserPrefStorage
JsonSerenityStorage .u.|> SerenityStorage
JsonQuestionStorage .u.|> QuestionStorage

@enduml
