@startuml
skinparam linetype ortho
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T1
skinparam classBackgroundColor UI_COLOR_T1

package Ui <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class TitleDisplay
Class ResultDisplay
Class CommandBox
Class SideBar
Class HelpWindow
}

package ui.datapanel {
Class Hidden #whitei
}

package Logic {
Class HiddenL #white
}

UiManager .right.|> Ui
UiManager -down-> MainWindow
MainWindow *--> ui.datapanel
MainWindow *-down-> TitleDisplay
MainWindow *-down-> ResultDisplay
MainWindow *-down-> CommandBox
MainWindow *-down-> SideBar
MainWindow *-down-> HelpWindow

MainWindow --down-|> UiPart
TitleDisplay --down-|> UiPart
ResultDisplay --down-|> UiPart
CommandBox --down-|> UiPart
SideBar --down-|> UiPart
HelpWindow --down-|> UiPart

ui.datapanel --|> UiPart

UiManager ---> Logic
MainWindow -right--> Logic

@enduml
