@startuml
skinparam linetype ortho
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T1
skinparam classBackgroundColor UI_COLOR_T1

package Ui {
Class MainWindow
Class "{abstract}\nUiPart" as UiPart

package Datapanel {
Class DataPanel
Class SerenityDataPanel
Class GroupDataPanel
Class LessonDataPanel
Class LessonCard
Class StudentCard
Class StudentInfoCard
Class QuestionCard
}

}

MainWindow *-down-> DataPanel

DataPanel <|-- SerenityDataPanel
DataPanel <|-- GroupDataPanel
DataPanel <|-- LessonDataPanel

SerenityDataPanel --> QuestionCard
GroupDataPanel --> LessonCard
GroupDataPanel --> StudentCard
LessonDataPanel --> StudentInfoCard
LessonDataPanel --> QuestionCard

DataPanel ---|> UiPart
StudentCard -down-|> UiPart
LessonCard -down-|> UiPart
StudentInfoCard -down-|> UiPart
QuestionCard -down-|> UiPart

@enduml
